# Generated by Django 4.0.1 on 2022-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo.'),
        ),
    ]
